# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "E:/dev/gbfpga/gbfpga.qpf"
set_global_assignment -name VHDL_FILE altera_europa_support.vhd
set_global_assignment -name SOURCE_FILE ./z80acc.vhd
project_close